version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOG_LEVEL: debug
    depends_on:
      - redis
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    command: npm run dev

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: