[phases.setup]
aptPkgs = ["curl", "git", "libssl-dev", "pkg-config", "libsqlite3-dev", "gnupg", "zlib1g-dev"]

[phases.install]
cmds = [
    "curl -fsSL https://download.swift.org/swift-5.9.2-release/ubuntu2204/swift-5.9.2-RELEASE/swift-5.9.2-RELEASE-ubuntu22.04.tar.gz -o swift.tar.gz",
    "tar -xzf swift.tar.gz",
    "export PATH=$PWD/swift-5.9.2-RELEASE-ubuntu22.04/usr/bin:$PATH",
    "swift --version"
]

[phases.build]
cmds = [
    "export PATH=$PWD/swift-5.9.2-RELEASE-ubuntu22.04/usr/bin:$PATH",
    "swift build -c release --product Run"
]

[start]
cmd = ".build/release/Run serve --env production --hostname 0.0.0.0 --port $PORT"