[phases.setup]
nixPkgs = ["swift", "openssl", "zlib", "pkg-config"]

[phases.build]
cmds = ["swift build -c release --product Run"]

[start]
cmd = ".build/release/Run serve --env production --hostname 0.0.0.0 --port ${PORT}"