[phases.setup]
nixPkgs = ["swift", "swiftPackages.swift-format", "pkg-config", "openssl"]

[phases.install]
cmds = ["swift package resolve"]

[phases.build]
cmds = ["swift build -c release"]

[start]
cmd = ".build/release/Run serve --env production --hostname 0.0.0.0 --port ${PORT}"