[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"
nixpacksConfigPath = "railway.json"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
PORT = "8080"