[build]
builder = "NIXPACKS"
buildCommand = "swift build -c release --product Run"

[deploy]
startCommand = ".build/release/Run serve --env production --hostname 0.0.0.0 --port ${PORT}"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[nixpacks]
swift_version = "5.9"

[[nixpacks.packages]]
name = "redis"
version = "latest"