[build]
builder = "NIXPACKS"
buildCommand = "swift build -c release"

[deploy]
startCommand = ".build/release/Run serve --env production --hostname 0.0.0.0 --port ${PORT}"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3